services:
  fresh-cart-be:
    environment:
      DATABASE_URL: postgresql://app_dev:dev_password@postgres/dev
      TEST_DATABASE_URL: postgresql://app_test:test_password@postgres/test
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      LANGCHAIN_API_KEY: ${LANGCHAIN_API_KEY}
      LANGCHAIN_PROJECT: freshcart
      LANGCHAIN_TRACING_V2: false
      LANGCHAIN_TAG: <ENTER_YOUR_TAG>
    build: backend
    image: fresh-cart-be
    working_dir: /usr/src/app/
    volumes:
      - ./backend/:/usr/src/app/
      - ./fresh-cart.log:/var/log/fresh-cart.log
    ports:
      - 9090:9090
    command: poetry run flask --debug --app freshcart/app run --host 0.0.0.0 --port 9090
    networks:
      - fresh-net
    depends_on:
      postgres:
        condition: service_healthy

  fresh-cart-dev-fe:
    build: frontend
    image: fresh-cart-dev-fe
    working_dir: /usr/src/app/
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - 4200:4200
    command: npm start
    networks:
      - fresh-net

  fresh-cart-prod-fe:
    image: nginx:1.19.0
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 4200:80
    networks:
      - fresh-net
    restart: on-failure

  postgres:
    image: ankane/pgvector:v0.4.1
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: app_dev
      POSTGRES_PASSWORD: dev_password
      ALLOW_IP_RANGE: "172.0.0.0/8"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "app_dev", "-d", "dev"]
      interval: 3s
      timeout: 3s
      retries: 5
    command: ["postgres", "-c", "log_statement=none"]
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./docker/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - ./db:/db
    networks:
      - fresh-net

networks:
  fresh-net:

volumes:
  pgdata:
