CREATE USER app_test;
CREATE DATABASE test;
GRANT ALL PRIVILEGES ON DATABASE test TO app_test;
ALTER DATABASE test OWNER TO app_test;
ALTER USER app_test WITH PASSWORD 'test_password';
CREATE EXTENSION IF NOT EXISTS vector;
\c test
CREATE EXTENSION IF NOT EXISTS vector;
