"""Add function to search embeddings

Revision ID: 6835574a8f98
Revises: fab82255fb82
Create Date: 2023-04-24 06:19:53.155681

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6835574a8f98"
down_revision = "fab82255fb82"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        create or replace function match_documents (
          query_embedding vector(1536),
          similarity_threshold float,
          match_count int
        )
        returns table (
          id bigint,
          content text,
          similarity float
        )
        language plpgsql
        as $$
        begin
          return query
          select
            CAST(documents.id AS bigint),
            CAST(documents.content as text),
            1 - (documents.embedding <=> query_embedding) as similarity
          from documents
          where 1 - (documents.embedding <=> query_embedding) > similarity_threshold
          order by documents.embedding <=> query_embedding
          limit match_count;
        end;
        $$;
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS match_documents;")
    # ### end Alembic commands ###
