"""Remove quantity from products model

Revision ID: 15f95019d26b
Revises: bae4c1f2ba5a
Create Date: 2023-05-08 10:39:45.891982

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "15f95019d26b"
down_revision = "bae4c1f2ba5a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products",
        sa.Column(
            "quantity", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
