"""remove documents

Revision ID: 25f7873ec0a6
Revises: 15f95019d26b
Create Date: 2023-11-21 14:21:22.486456

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "25f7873ec0a6"
down_revision = "15f95019d26b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("documents")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "embedding", sa.NullType(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="documents_pkey"),
    )
    # ### end Alembic commands ###
