"""Add quantity and price column to products table

Revision ID: ab165c8630f7
Revises: 6835574a8f98
Create Date: 2023-04-24 13:03:56.220142

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab165c8630f7"
down_revision = "6835574a8f98"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("quantity", sa.Integer(), nullable=True)
    )
    op.add_column("products", sa.Column("price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "price")
    op.drop_column("products", "quantity")
    # ### end Alembic commands ###
