"""add embedding to products

Revision ID: b6bc0f62f96b
Revises: 25f7873ec0a6
Create Date: 2023-11-21 14:22:08.542990

"""
import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision = "b6bc0f62f96b"
down_revision = "25f7873ec0a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("embedding", Vector(dim=1536), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "embedding")
    # ### end Alembic commands ###
